version: '3.7'
services:
    sgbp-web:
        build: .
        image: sgbp-web
        environment:
            - JDBC_URL=jdbc:postgresql://sgbp-postgresql:5432/infraestructura
            - JDBC_USERNAME=ingraestructura
            - JDBC_PASSWORD=ingraestructura
        ports:
            - "8080:80"
        depends_on:
            - sgbp-postgresql
        networks:
            - monolito
    sgbp-postgresql:
     extends:
        file: postgresql.yml
        service: sgbp-postgresql

networks:
  monolito: {}